# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/phaneendrayeluri/gokit101
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: go build ./...
  whereami:
    docker:
      - image: circleci/golang:1.9
    steps:
      - pwd
workflow:
  version: 2
  feature-branch-only:
    jobs:
      - build
      - whereami
      filters:
        branches: 
          ignore: /^(?!feature).*/

